services:
  db:
    image: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SEQ_DATABASE}
      MYSQL_USER: ${SEQ_USERNAME}
      MYSQL_PASSWORD: ${SEQ_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - lag

  phpmyadmin:
    image: phpmyadmin
    restart: no
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${SEQ_USERNAME}
      PMA_PASSWORD: ${SEQ_PASSWORD}
    depends_on:
      - db
    networks:
      - lag

  mongo:
    image: mongo
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - lag

  mongoku:
    image: huggingface/mongoku
    restart: no
    ports:
      - "3100:3100"
    environment:
      MONGOKU_DEFAULT_HOST: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017
    depends_on:
      - mongo
    networks:
      - lag

networks:
  lag:
    driver: bridge
