services:
  db:
    image: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SEQ_DATABASE}
      MYSQL_USER: ${SEQ_USERNAME}
      MYSQL_PASSWORD: ${SEQ_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - lag

  phpmyadmin:
    image: phpmyadmin
    restart: no
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${SEQ_USERNAME}
      PMA_PASSWORD: ${SEQ_PASSWORD}
    depends_on:
      - db
    networks:
      - lag

networks:
  lag:
    driver: bridge
