import { IUserRepository } from "../../domain/repositories/user/IUserRepository";

export const mockUserRepo = (): jest.Mocked<IUserRepository> => ({
  getManyByIds: jest.fn().mockResolvedValue([]),
  getAll: jest.fn(),
  getById: jest.fn().mockResolvedValue(null),
  getByEmail: jest.fn().mockResolvedValue(null),
  getByIdWithPassword: jest.fn().mockResolvedValue(null),
  getReachableByEmail: jest.fn().mockResolvedValue(null),
  holderOf: jest.fn().mockResolvedValue(null),
  forgetDevices: jest.fn().mockResolvedValue(null),
  updateWithTokenBump: jest.fn(),
  recordLogin: jest.fn().mockResolvedValue(undefined),
  resetPassword: jest.fn().mockResolvedValue(null),
  markEmailVerified: jest.fn().mockResolvedValue(null),
  startEmailChange: jest.fn(),
  addUndoLink: jest.fn().mockResolvedValue(true),
  dropUndoLink: jest.fn().mockResolvedValue(undefined),
  renewEmailChange: jest.fn(),
  dropEmailChange: jest.fn().mockResolvedValue(undefined),
  applyEmailChange: jest.fn(),
  getForUndo: jest.fn().mockResolvedValue(null),
  undoEmailChange: jest.fn(),
  markDeleted: jest.fn().mockResolvedValue(null),
  restoreDeleted: jest.fn().mockResolvedValue(null),
  restoreFromLink: jest.fn().mockResolvedValue(null),
  listUndatedDeletions: jest.fn().mockResolvedValue([]),
  setKeptUntil: jest.fn().mockResolvedValue(undefined),
  listErasable: jest.fn().mockResolvedValue([]),
  claimErasure: jest.fn().mockResolvedValue(true),
  eraseForGood: jest.fn().mockResolvedValue(undefined),
  listWithoutDeadline: jest.fn().mockResolvedValue([]),
  startConfirmDeadline: jest.fn().mockResolvedValue(true),
  listDueReminders: jest.fn().mockResolvedValue([]),
  markReminded: jest.fn().mockResolvedValue(true),
  create: jest.fn(),
  update: jest.fn(),
});
