/**
 * The parity scenarios, authored by hand. Every row is here because it breaks
 * a plausible shortcut in a client-side derivation — the `note` says which.
 *
 * Ids are fixed so the frontend's tests can hard-code them. Dates carry the
 * offset the user would have typed, never `Z`: a fixture about timezones that
 * states its instants in UTC hides exactly what it is meant to pin down.
 */
import { Scenario } from "./types";

/** `01930001-…-00000000a001`: scenario 1, kind `a` (account), number 1. */
export const fixtureId = (
  scenario: number,
  kind: "u" | "a" | "c" | "t" | "b" | "k" | "g" | "s" | "p",
  n: number,
): string =>
  `0193000${scenario}-0000-7000-8000-0000000${kind}${String(n).padStart(4, "0")}`;

const bogota: Scenario = {
  id: "cop-bogota",
  title: "COP · America/Bogota · zero-decimal currency, fixed −05:00 offset",
  pins: [
    "A day bucket is the day in the USER's timezone: 23:30 in Bogota is already tomorrow in UTC.",
    "A month window is [first day 00:00 local, next month 00:00 local) — not a UTC month.",
    "Deleted transactions leave every figure: totals, buckets, budgets and balances.",
    "ADJUSTMENT moves a balance but is excluded from spending unless asked for by name.",
    "TRANSFER moves two balances and is not spending, but it can carry a category.",
    "An archived category keeps its totals; archiving is not deleting.",
    "Quick-adds count as spending under `uncategorized`, and are the pending summary.",
    "Tag buckets double-count a transaction with two tags: their sum exceeds the total.",
    "With no `type`, the server means EXPENSE + INCOME + TRANSFER: everything but ADJUSTMENT and SETTLEMENT.",
    "`type: TRANSFER` is a spending query like any other: it groups transfers by their category.",
    "A transfer with no category lands in `uncategorized`, beside the ones that have one.",
    "An account bucket is the account the money left; a quick-add leaves the default one, and a transfer is keyed by its origin, never by both ends.",
    "A month bucket is the first seven characters of the frozen day, so months and days agree.",
    "A category filter drops the quick-adds with it: they have no category to match.",
    "A LISTING has no opinion about spending: with no `type` it shows the transfer and the adjustment too.",
    "Two rows with the same amount are ordered by id, in the direction the page runs.",
    "A backdated row lands by its own date, not by when it was written: id order is not date order.",
  ],
  user: {
    id: fixtureId(1, "u", 1),
    timezone: "America/Bogota",
    currency: "COP",
    minorUnits: 0,
  },
  reference: "2026-08-20T12:00:00-05:00",
  accounts: [
    {
      key: "bank",
      name: "Bancolombia",
      type: "ACCOUNT",
      color: "BLUE",
      openingBalance: 1_000_000,
      isDefault: true,
    },
    {
      key: "cash",
      name: "Cash",
      type: "CASH",
      color: "GRAY",
      openingBalance: 200_000,
    },
    {
      key: "card",
      name: "Visa Gold",
      type: "CARD",
      color: "PURPLE",
      openingBalance: -500_000,
    },
    {
      key: "savings",
      name: "Savings",
      type: "SAVINGS",
      color: "GREEN",
      openingBalance: 5_000_000,
    },
    {
      key: "closed",
      name: "Nequi",
      type: "OTHER",
      color: "PINK",
      openingBalance: 0,
      archived: true,
    },
  ],
  categories: [
    { key: "food", name: "Food", type: "EXPENSE" },
    { key: "transport", name: "Transport", type: "EXPENSE" },
    { key: "coffee", name: "Coffee", type: "EXPENSE" },
    { key: "trips", name: "Trips", type: "EXPENSE", archived: true },
    { key: "salary", name: "Salary", type: "INCOME" },
    { key: "card-payment", name: "Card payment", type: "TRANSFER" },
  ],
  transactions: [
    {
      key: "late-july-groceries",
      type: "EXPENSE",
      amount: 30_000,
      date: "2026-07-31T23:30:00-05:00",
      description: "Corner store",
      category: "food",
      from: "bank",
      tags: ["groceries"],
      note: "04:30Z on 2026-08-01: a UTC day bucket files it under August, the user under 31 July.",
    },
    {
      key: "salary",
      type: "INCOME",
      amount: 4_000_000,
      date: "2026-08-01T09:00:00-05:00",
      description: "August salary",
      category: "salary",
      to: "bank",
    },
    {
      key: "market",
      type: "EXPENSE",
      amount: 85_000,
      date: "2026-08-03T12:00:00-05:00",
      description: "Carulla groceries",
      category: "food",
      from: "bank",
      tags: ["groceries"],
    },
    {
      key: "same-day-coffee",
      type: "EXPENSE",
      amount: 9_800,
      date: "2026-08-03T19:45:00-05:00",
      description: "Pergamino",
      category: "coffee",
      from: "cash",
      tags: ["coffee"],
      note: "Second row of 2026-08-03, so that day's bucket has a count and an average.",
    },
    {
      key: "bus",
      type: "EXPENSE",
      amount: 12_000,
      date: "2026-08-05T08:15:00-05:00",
      description: "TransMilenio",
      category: "transport",
      from: "cash",
      tags: ["work"],
    },
    {
      key: "to-savings",
      type: "TRANSFER",
      amount: 500_000,
      date: "2026-08-10T10:00:00-05:00",
      description: "Monthly savings",
      from: "bank",
      to: "savings",
      note: "Moves two balances and is not spending.",
    },
    {
      key: "pay-the-card",
      type: "TRANSFER",
      amount: 300_000,
      date: "2026-08-11T09:15:00-05:00",
      description: "Visa Gold",
      category: "card-payment",
      from: "bank",
      to: "card",
      note: "A transfer can carry a category, so it has a bucket of its own under `type: TRANSFER`.",
    },
    {
      key: "flight",
      type: "EXPENSE",
      amount: 250_000,
      date: "2026-08-12T16:20:00-05:00",
      description: "Avianca",
      category: "trips",
      from: "card",
      tags: ["travel"],
      note: "Its category is archived and it still counts.",
    },
    {
      key: "cash-count",
      type: "ADJUSTMENT",
      amount: 7_500,
      date: "2026-08-14T07:05:00-05:00",
      description: "Cash count correction",
      to: "cash",
      note: "Moves the balance; excluded from spending unless type=ADJUSTMENT is asked for.",
    },
    {
      key: "dinner",
      type: "EXPENSE",
      amount: 42_500,
      date: "2026-08-18T21:00:00-05:00",
      description: "Rappi dinner",
      category: "food",
      from: "card",
      note: "No tags: lands in the `untagged` bucket.",
    },
    {
      key: "latte",
      type: "EXPENSE",
      amount: 11_300,
      date: "2026-08-20T13:00:00-05:00",
      description: "Juan Valdez",
      category: "coffee",
      from: "card",
      tags: ["coffee", "latte"],
      note: "Two tags: counted once in the total, twice across the tag buckets.",
    },
    {
      key: "taxi",
      type: "EXPENSE",
      amount: 18_400,
      date: "2026-08-22T11:30:00-05:00",
      description: "Uber to work",
      category: "transport",
      from: "bank",
      tags: ["work"],
    },
    {
      key: "quick-lunch",
      type: "EXPENSE",
      amount: 12_500,
      date: "2026-08-24T18:00:00-05:00",
      quick: true,
      note: "Quick-add: no category, pending review, charged to the default account.",
    },
    {
      key: "quick-errand",
      type: "EXPENSE",
      amount: 20_000,
      date: "2026-08-25T18:30:00-05:00",
      quick: true,
    },
    {
      key: "refunded",
      type: "EXPENSE",
      amount: 99_000,
      date: "2026-08-26T12:00:00-05:00",
      description: "Returned purchase",
      category: "food",
      from: "bank",
      deleted: true,
      note: "Deleted: absent from every figure, and its balance effect is reversed.",
    },
    {
      key: "second-bus",
      type: "EXPENSE",
      amount: 12_000,
      date: "2026-08-28T07:40:00-05:00",
      description: "TransMilenio",
      category: "transport",
      from: "cash",
      tags: ["work"],
      note: "The same amount as `bus`: a list ordered by amount has to break the tie by id, not by luck.",
    },
    {
      key: "backdated-market",
      type: "EXPENSE",
      amount: 63_000,
      date: "2026-08-02T10:00:00-05:00",
      description: "Plaza de mercado",
      category: "food",
      from: "bank",
      tags: ["groceries"],
      note: "Written last, dated the 2nd: after this row, ordering by id is not ordering by date.",
    },
    {
      key: "last-minute-coffee",
      type: "EXPENSE",
      amount: 4_700,
      date: "2026-08-31T23:30:00-05:00",
      description: "Tinto",
      category: "coffee",
      from: "cash",
      tags: ["coffee"],
      note: "04:30Z on 2026-09-01: inside August for the user, outside it in UTC.",
    },
  ],
  budgets: [
    {
      key: "everything",
      name: "Everything",
      categories: [],
      amount: 2_000_000,
      periodType: "MONTHLY",
      effectiveFrom: "2026-06-01T00:00:00-05:00",
      note: "Global: spends the window's whole expense, quick-adds included.",
    },
    {
      key: "food",
      name: "Food",
      categories: ["food"],
      amount: 150_000,
      periodType: "MONTHLY",
      effectiveFrom: "2026-06-01T00:00:00-05:00",
      override: 180_000,
      note: "The override applies to the reference period only; baseAmount stays 150 000.",
    },
    {
      key: "coffee",
      name: "Coffee",
      categories: ["coffee"],
      amount: 30_000,
      periodType: "WEEKLY",
      effectiveFrom: "2026-06-01T00:00:00-05:00",
      note: "ISO week (Monday-based) resolved in the user's timezone.",
    },
    {
      key: "transport",
      name: "Transport",
      categories: ["transport"],
      amount: 60_000,
      periodType: "BIWEEKLY",
      effectiveFrom: "2026-06-01T00:00:00-05:00",
      note: "Two-week grid anchored on the week of 2024-01-01, not on the budget.",
    },
    {
      key: "trip",
      name: "August trip",
      categories: ["trips"],
      amount: 300_000,
      periodType: "CUSTOM",
      periodStartDate: "2026-08-10T00:00:00-05:00",
      periodEndDate: "2026-08-31T00:00:00-05:00",
      note: "Its only category is archived: archivedCategoryIds is not empty.",
    },
    {
      key: "old-trip",
      name: "July trip",
      categories: ["transport"],
      amount: 100_000,
      periodType: "CUSTOM",
      periodStartDate: "2026-07-01T00:00:00-05:00",
      periodEndDate: "2026-08-01T00:00:00-05:00",
      note: "Expired at the reference instant: still listed, flagged.",
    },
    {
      key: "retired",
      name: "Retired budget",
      categories: ["coffee"],
      amount: 40_000,
      periodType: "MONTHLY",
      effectiveFrom: "2026-06-01T00:00:00-05:00",
      archived: true,
      note: "Archived: out of the views, present in the sync feed with archivedAt.",
    },
  ],
  spending: [
    {
      name: "august-by-category",
      groupBy: "category",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
    },
    {
      name: "august-by-tag",
      groupBy: "tag",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "The buckets add up to more than `total`: one transaction carries two tags.",
    },
    {
      name: "july-31-to-august-by-day",
      groupBy: "day",
      type: "EXPENSE",
      from: "2026-07-31T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "Widened by a day so the 31 July bucket shows up next to August's.",
    },
    {
      name: "august-by-category-untyped",
      groupBy: "category",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "No `type`: income and the transfer are in, only ADJUSTMENT is out.",
    },
    {
      name: "august-transfers-by-category",
      groupBy: "category",
      type: "TRANSFER",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "What the Recent row of a transfer asks for. One transfer has a category and one does not.",
    },
    {
      name: "august-transfers-by-account",
      groupBy: "account",
      type: "TRANSFER",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "A transfer is the row with two accounts, and it is bucketed by the one the money left.",
    },
    {
      name: "august-by-account",
      groupBy: "account",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "The two quick-adds land on the default account, which is where the server charged them.",
    },
    {
      name: "july-and-august-by-month",
      groupBy: "month",
      type: "EXPENSE",
      from: "2026-07-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "Two months in one request. The 31 July row is July here and in the day buckets.",
    },
    {
      name: "august-by-day-in-two-categories",
      groupBy: "day",
      type: "EXPENSE",
      categories: ["food", "coffee"],
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "What a budget of two categories asks for: its own per-day chart. No quick-add matches.",
    },
    {
      name: "july-and-august-by-month-and-category",
      groupBy: "month",
      splitBy: "category",
      type: "EXPENSE",
      from: "2026-07-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "One request instead of one per month: each month's splits add up to its own total.",
    },
  ],
  lists: [
    {
      name: "august-biggest",
      sort: "amount",
      order: "desc",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      limit: 5,
      note: "The five biggest of the period, asked for instead of read page by page.",
    },
    {
      name: "august-by-amount-ascending",
      sort: "amount",
      order: "asc",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      limit: 100,
      note: "`bus` and `second-bus` both cost 12 000: ascending, the smaller id comes first.",
    },
    {
      name: "august-by-amount-descending",
      sort: "amount",
      order: "desc",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      limit: 100,
      note: "The same tie in the default direction: descending, the larger id comes first.",
    },
    {
      name: "august-newest-every-type",
      sort: "date",
      order: "desc",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      limit: 100,
      note: "The default order, and with no `type` the transfer and the adjustment are listed.",
    },
    {
      name: "august-oldest-first",
      sort: "date",
      order: "asc",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      limit: 100,
      note: "`backdated-market` opens this list and is one of the last by id: the two orders differ.",
    },
    {
      name: "august-biggest-in-two-categories",
      sort: "amount",
      order: "desc",
      type: "EXPENSE",
      categories: ["food", "coffee"],
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      limit: 5,
      note: "What a budget of two categories asks for; the quick-adds have no category and stay out.",
    },
  ],
};

const madrid: Scenario = {
  id: "eur-madrid",
  title: "EUR · Europe/Madrid · two decimals and the spring DST jump",
  pins: [
    "Amounts with decimals only add up exactly in minor units: the `current` balance, 1000 − 10.10 + 1500 − 7.77 − 100 − 3.45, drifts to 2378.6800000000003 as a float sum.",
    "A March window opens at +01:00 and closes at +02:00: its ends have different offsets.",
    "2026-03-29 is a 23-hour day — the local times 02:00–02:59 do not exist.",
    "A transaction 5 minutes into April is UTC-March: a UTC window would take it and drop the one on 1 March.",
    "An average is rounded in minor units: 20.29 over 3 rows is 6.76.",
  ],
  user: {
    id: fixtureId(2, "u", 1),
    timezone: "Europe/Madrid",
    currency: "EUR",
    minorUnits: 2,
  },
  reference: "2026-03-25T12:00:00+01:00",
  accounts: [
    {
      key: "current",
      name: "Cuenta corriente",
      type: "ACCOUNT",
      color: "BLUE",
      openingBalance: 1_000,
      isDefault: true,
    },
    {
      key: "card",
      name: "Tarjeta",
      type: "CARD",
      color: "RED",
      openingBalance: -250.5,
    },
  ],
  categories: [
    { key: "groceries", name: "Compra", type: "EXPENSE" },
    { key: "dining", name: "Restaurantes", type: "EXPENSE" },
    { key: "subs", name: "Suscripciones", type: "EXPENSE" },
    { key: "salary", name: "Nómina", type: "INCOME" },
  ],
  transactions: [
    {
      key: "first-minutes",
      type: "EXPENSE",
      amount: 10.1,
      date: "2026-03-01T00:15:00+01:00",
      description: "Mercadona",
      category: "groceries",
      from: "current",
      tags: ["compra"],
      note: "23:15Z on 28 February: inside March for the user, outside it in UTC.",
    },
    {
      key: "payday",
      type: "INCOME",
      amount: 1_500,
      date: "2026-03-05T09:00:00+01:00",
      description: "Nómina",
      category: "salary",
      to: "current",
    },
    {
      key: "before-the-jump",
      type: "EXPENSE",
      amount: 0.1,
      date: "2026-03-29T01:45:00+01:00",
      description: "Propina",
      category: "dining",
      from: "card",
      note: "15 minutes before the clocks jump from 02:00 to 03:00.",
    },
    {
      key: "after-the-jump",
      type: "EXPENSE",
      amount: 0.2,
      date: "2026-03-29T03:15:00+02:00",
      description: "Café",
      category: "dining",
      from: "card",
      note: "30 real minutes after the previous row, and 1h30 later on the clock.",
    },
    {
      key: "sunday-lunch",
      type: "EXPENSE",
      amount: 19.99,
      date: "2026-03-29T21:00:00+02:00",
      description: "Comida",
      category: "dining",
      from: "card",
      tags: ["finde"],
    },
    {
      key: "rounding",
      type: "EXPENSE",
      amount: 2.3,
      date: "2026-03-30T12:00:00+02:00",
      description: "Menú",
      category: "dining",
      from: "card",
      tags: ["finde"],
    },
    {
      key: "subscription",
      type: "EXPENSE",
      amount: 7.77,
      date: "2026-03-31T23:59:00+02:00",
      description: "Spotify",
      category: "subs",
      from: "current",
      note: "Last minute of March, local time.",
    },
    {
      key: "next-month",
      type: "EXPENSE",
      amount: 100,
      date: "2026-04-01T00:05:00+02:00",
      description: "Compra de abril",
      category: "groceries",
      from: "current",
      note: "22:05Z on 31 March: a UTC window would count it in March.",
    },
    {
      key: "void",
      type: "EXPENSE",
      amount: 50,
      date: "2026-03-20T12:00:00+01:00",
      description: "Devolución",
      category: "groceries",
      from: "current",
      deleted: true,
    },
    {
      key: "pending-coffee",
      type: "EXPENSE",
      amount: 3.45,
      date: "2026-03-27T17:00:00+01:00",
      quick: true,
    },
  ],
  budgets: [
    {
      key: "dining-month",
      name: "Restaurantes",
      categories: ["dining"],
      amount: 40,
      periodType: "MONTHLY",
      effectiveFrom: "2026-01-01T00:00:00+01:00",
    },
    {
      key: "dining-week",
      name: "Restaurantes (semana)",
      categories: ["dining"],
      amount: 25,
      periodType: "WEEKLY",
      effectiveFrom: "2026-01-01T00:00:00+01:00",
      note: "The week of the jump lasts 167 hours, not 168.",
    },
    {
      key: "everything",
      name: "Todo",
      categories: [],
      amount: 100,
      periodType: "MONTHLY",
      effectiveFrom: "2026-01-01T00:00:00+01:00",
    },
  ],
  spending: [
    {
      name: "march-by-category",
      groupBy: "category",
      type: "EXPENSE",
      from: "2026-03-01T00:00:00+01:00",
      to: "2026-04-01T00:00:00+02:00",
      note: "The window's ends carry different offsets. That is the point.",
    },
    {
      name: "march-by-day",
      groupBy: "day",
      type: "EXPENSE",
      from: "2026-03-01T00:00:00+01:00",
      to: "2026-04-01T00:00:00+02:00",
    },
    {
      name: "march-by-account",
      groupBy: "account",
      type: "EXPENSE",
      from: "2026-03-01T00:00:00+01:00",
      to: "2026-04-01T00:00:00+02:00",
    },
    {
      name: "march-and-april-by-month-and-category",
      groupBy: "month",
      splitBy: "category",
      type: "EXPENSE",
      from: "2026-03-01T00:00:00+01:00",
      to: "2026-05-01T00:00:00+02:00",
      note: "The row 5 minutes into April is April's, in the month buckets as in the day ones.",
    },
  ],
  lists: [
    {
      name: "march-biggest",
      sort: "amount",
      order: "desc",
      type: "EXPENSE",
      from: "2026-03-01T00:00:00+01:00",
      to: "2026-04-01T00:00:00+02:00",
      limit: 3,
      note: "Ordered in minor units: 19.99 before 10.10 before 7.77.",
    },
  ],
};

const tokyo: Scenario = {
  id: "jpy-tokyo",
  title: "JPY · Asia/Tokyo · zero decimals, +09:00, quarter and year windows",
  pins: [
    "A local day starts at 15:00Z the day before: 00:10 on 1 April is 31 March in UTC.",
    "Quarter keys are `2026-Q2`; the year window is the local year, not 1 January UTC.",
    "A budget with no spend reports 0, not a missing figure.",
    "JPY has no minor unit: the amounts are the integers as typed.",
  ],
  user: {
    id: fixtureId(3, "u", 1),
    timezone: "Asia/Tokyo",
    currency: "JPY",
    minorUnits: 0,
  },
  reference: "2026-05-15T12:00:00+09:00",
  accounts: [
    {
      key: "bank",
      name: "銀行",
      type: "ACCOUNT",
      color: "BLUE",
      openingBalance: 500_000,
      isDefault: true,
    },
    {
      key: "wallet",
      name: "財布",
      type: "CASH",
      color: "GRAY",
      openingBalance: 20_000,
    },
  ],
  categories: [
    { key: "rent", name: "家賃", type: "EXPENSE" },
    { key: "transit", name: "交通", type: "EXPENSE" },
    { key: "gifts", name: "贈り物", type: "EXPENSE" },
    { key: "salary", name: "給与", type: "INCOME" },
  ],
  transactions: [
    {
      key: "march-rent",
      type: "EXPENSE",
      amount: 120_000,
      date: "2026-03-31T23:30:00+09:00",
      description: "3月家賃",
      category: "rent",
      from: "bank",
      note: "14:30Z: the last half hour of Q1 in Tokyo.",
    },
    {
      key: "first-ride",
      type: "EXPENSE",
      amount: 1_200,
      date: "2026-04-01T00:10:00+09:00",
      description: "定期",
      category: "transit",
      from: "wallet",
      note: "15:10Z on 31 March: Q2 for the user, Q1 in UTC.",
    },
    {
      key: "gift",
      type: "EXPENSE",
      amount: 8_800,
      date: "2026-04-15T12:00:00+09:00",
      description: "お祝い",
      category: "gifts",
      from: "wallet",
    },
    {
      key: "quarter-end",
      type: "EXPENSE",
      amount: 780,
      date: "2026-06-30T23:59:00+09:00",
      description: "バス",
      category: "transit",
      from: "wallet",
      note: "Last minute of Q2.",
    },
    {
      key: "next-quarter",
      type: "EXPENSE",
      amount: 15_000,
      date: "2026-07-01T00:01:00+09:00",
      description: "お中元",
      category: "gifts",
      from: "bank",
      note: "One minute into Q3: out of the quarter, inside the year.",
    },
    {
      key: "payday",
      type: "INCOME",
      amount: 350_000,
      date: "2026-04-25T09:00:00+09:00",
      description: "給与",
      category: "salary",
      to: "bank",
    },
    {
      key: "pending-lunch",
      type: "EXPENSE",
      amount: 500,
      date: "2026-05-02T12:30:00+09:00",
      quick: true,
    },
    {
      key: "void-ride",
      type: "EXPENSE",
      amount: 300,
      date: "2026-05-10T08:00:00+09:00",
      category: "transit",
      from: "wallet",
      deleted: true,
    },
  ],
  budgets: [
    {
      key: "transit-quarter",
      name: "交通",
      categories: ["transit"],
      amount: 5_000,
      periodType: "QUARTERLY",
      effectiveFrom: "2026-01-01T00:00:00+09:00",
    },
    {
      key: "year",
      name: "年間",
      categories: [],
      amount: 2_000_000,
      periodType: "YEARLY",
      effectiveFrom: "2026-01-01T00:00:00+09:00",
    },
    {
      key: "gifts-month",
      name: "贈り物",
      categories: ["gifts"],
      amount: 10_000,
      periodType: "MONTHLY",
      effectiveFrom: "2026-01-01T00:00:00+09:00",
      note: "May has no gift: the budget reports 0 spent.",
    },
  ],
  spending: [
    {
      name: "q2-by-category",
      groupBy: "category",
      type: "EXPENSE",
      from: "2026-04-01T00:00:00+09:00",
      to: "2026-07-01T00:00:00+09:00",
    },
    {
      name: "q2-by-day",
      groupBy: "day",
      type: "EXPENSE",
      from: "2026-04-01T00:00:00+09:00",
      to: "2026-07-01T00:00:00+09:00",
    },
    {
      name: "q2-by-month",
      groupBy: "month",
      type: "EXPENSE",
      from: "2026-04-01T00:00:00+09:00",
      to: "2026-07-01T00:00:00+09:00",
      note: "Three months, and 2026-04 holds the row that UTC would file in March.",
    },
    {
      name: "q2-by-day-in-two-categories",
      groupBy: "day",
      type: "EXPENSE",
      categories: ["transit", "gifts"],
      from: "2026-04-01T00:00:00+09:00",
      to: "2026-07-01T00:00:00+09:00",
      note: "The quick-add has no category, so naming categories leaves it out.",
    },
  ],
  lists: [
    {
      name: "q2-biggest",
      sort: "amount",
      order: "desc",
      type: "EXPENSE",
      from: "2026-04-01T00:00:00+09:00",
      to: "2026-07-01T00:00:00+09:00",
      limit: 3,
    },
  ],
};

const newYork: Scenario = {
  id: "usd-new-york",
  title: "USD · America/New_York · the repeated hour and an INCOME budget",
  pins: [
    "The autumn DST change repeats an hour: 01:30 happens twice on 2025-11-02, one real hour apart, and both are that same day.",
    "November opens at −04:00 and closes at −05:00: the month is 721 hours long, not 720.",
    "`avg` rounds half up in minor units: 10.01 over 2 rows is 5.01, not 5.00.",
    "A budget's `type` filters the rows: an INCOME budget ignores every expense in its own window.",
    "A query for `type: INCOME` groups income by category the same way expenses are grouped.",
    "An INCOME bucket is keyed by the account the money reached, not the one it left.",
  ],
  user: {
    id: fixtureId(4, "u", 1),
    timezone: "America/New_York",
    currency: "USD",
    minorUnits: 2,
  },
  reference: "2025-11-15T12:00:00-05:00",
  accounts: [
    {
      key: "checking",
      name: "Checking",
      type: "ACCOUNT",
      color: "BLUE",
      openingBalance: 2_500,
      isDefault: true,
    },
    {
      key: "credit",
      name: "Credit card",
      type: "CARD",
      color: "PURPLE",
      openingBalance: -875.25,
    },
  ],
  categories: [
    { key: "rent", name: "Rent", type: "EXPENSE" },
    { key: "dining", name: "Dining", type: "EXPENSE" },
    { key: "salary", name: "Salary", type: "INCOME" },
    { key: "freelance", name: "Freelance", type: "INCOME" },
  ],
  transactions: [
    {
      key: "first-hour",
      type: "EXPENSE",
      amount: 12.34,
      date: "2025-11-01T00:30:00-04:00",
      description: "Late dinner",
      category: "dining",
      from: "credit",
      note: "04:30Z on 1 November: still October in nothing, but the first row of the month locally.",
    },
    {
      key: "first-one-thirty",
      type: "EXPENSE",
      amount: 5,
      date: "2025-11-02T01:30:00-04:00",
      description: "Diner, before the clocks go back",
      category: "dining",
      from: "credit",
      note: "05:30Z. The first 01:30 of the day: the clocks have not gone back yet.",
    },
    {
      key: "second-one-thirty",
      type: "EXPENSE",
      amount: 5.01,
      date: "2025-11-02T01:30:00-05:00",
      description: "Diner, after the clocks go back",
      category: "dining",
      from: "credit",
      note: "06:30Z. The SECOND 01:30 of the same day: one real hour later, same reading on the clock.",
    },
    {
      key: "rent",
      type: "EXPENSE",
      amount: 1_850,
      date: "2025-11-03T09:00:00-05:00",
      description: "November rent",
      category: "rent",
      from: "checking",
    },
    {
      key: "paycheck",
      type: "INCOME",
      amount: 3_200,
      date: "2025-11-14T09:00:00-05:00",
      description: "Paycheck",
      category: "salary",
      to: "checking",
    },
    {
      key: "side-gig",
      type: "INCOME",
      amount: 450.5,
      date: "2025-11-21T16:00:00-05:00",
      description: "Invoice #14",
      category: "freelance",
      to: "checking",
    },
    {
      key: "quick-coffee",
      type: "EXPENSE",
      amount: 8.25,
      date: "2025-11-18T15:20:00-05:00",
      quick: true,
    },
    {
      key: "refunded",
      type: "EXPENSE",
      amount: 60,
      date: "2025-11-10T13:00:00-05:00",
      description: "Returned order",
      category: "dining",
      from: "credit",
      deleted: true,
    },
    {
      key: "last-minute",
      type: "EXPENSE",
      amount: 27.75,
      date: "2025-11-30T23:59:00-05:00",
      description: "Sunday takeout",
      category: "dining",
      from: "credit",
      note: "04:59Z on 1 December: the last minute of November for the user.",
    },
    {
      key: "next-month",
      type: "EXPENSE",
      amount: 99.99,
      date: "2025-12-01T00:10:00-05:00",
      description: "December groceries",
      category: "dining",
      from: "credit",
      note: "Ten minutes into December: out of every November figure.",
    },
  ],
  budgets: [
    {
      key: "income-goal",
      name: "Monthly income",
      type: "INCOME",
      categories: ["salary", "freelance"],
      amount: 3_500,
      periodType: "MONTHLY",
      effectiveFrom: "2025-01-01T00:00:00-05:00",
      note: "An INCOME budget: the 1 908.35 of expenses in the same window count for nothing here.",
    },
    {
      key: "dining",
      name: "Dining out",
      categories: ["dining"],
      amount: 60,
      periodType: "MONTHLY",
      effectiveFrom: "2025-01-01T00:00:00-05:00",
    },
    {
      key: "everything",
      name: "All spending",
      categories: [],
      amount: 2_500,
      periodType: "MONTHLY",
      effectiveFrom: "2025-01-01T00:00:00-05:00",
    },
  ],
  spending: [
    {
      name: "november-by-category",
      groupBy: "category",
      type: "EXPENSE",
      from: "2025-11-01T00:00:00-04:00",
      to: "2025-12-01T00:00:00-05:00",
      note: "721 hours: the window opens on daylight time and closes on standard time.",
    },
    {
      name: "november-by-day",
      groupBy: "day",
      type: "EXPENSE",
      from: "2025-11-01T00:00:00-04:00",
      to: "2025-12-01T00:00:00-05:00",
      note: "Both 01:30s land on 2025-11-02, and their average rounds half up.",
    },
    {
      name: "november-income-by-category",
      groupBy: "category",
      type: "INCOME",
      from: "2025-11-01T00:00:00-04:00",
      to: "2025-12-01T00:00:00-05:00",
    },
    {
      name: "november-income-by-account",
      groupBy: "account",
      type: "INCOME",
      from: "2025-11-01T00:00:00-04:00",
      to: "2025-12-01T00:00:00-05:00",
      note: "Income buckets by the account it arrived in: by `fromAccountId` both rows would be unassigned.",
    },
    {
      name: "november-by-month-and-category",
      groupBy: "month",
      splitBy: "category",
      type: "EXPENSE",
      from: "2025-11-01T00:00:00-04:00",
      to: "2025-12-01T00:00:00-05:00",
      note: "One month, split: the two 01:30s are both dining and land in the same split.",
    },
  ],
  lists: [
    {
      name: "november-income-biggest",
      sort: "amount",
      order: "desc",
      type: "INCOME",
      from: "2025-11-01T00:00:00-04:00",
      to: "2025-12-01T00:00:00-05:00",
      limit: 5,
    },
  ],
};

/**
 * COP again, and on purpose: the currency with no minor unit is where a split
 * leaves a remainder and where two implementations drift. Everything shared
 * lives here — the four modes, a block of guests, several payers, a payment
 * imputed oldest line first, one in cash the app never saw, and a write-off
 * that moves no figure at all.
 */
const shared: Scenario = {
  id: "cop-shared",
  title:
    "COP · America/Bogota · the split, the imputation and what counts as yours",
  pins: [
    "100.000 between three does not divide: the odd peso is whoever fronted it.",
    "A block of twenty guests weighs twenty parts and is one party to collect from.",
    "A payment covers the oldest line first, across the whole group.",
    "Cash outside the app moves no account and lowers what counts as yours all the same.",
    "A write-off gives up on what was open and moves no figure.",
    "What Stats and the budgets measure is what is left as yours, never the amount.",
    "The oldest line is the oldest by DATE: one written last but dated first is covered first.",
    "Two lines on the same instant are covered in id order, so two devices agree.",
    "A fixed share plus the rest divided: the pinned figure never moves.",
    "More than they owed stays on the counter as surplus; nothing is over-collected.",
    "A write-off keeps the ceiling it was decided against: what is paid later lowers what it gives up.",
  ],
  user: {
    id: "01930005-0000-7000-8000-00000000u005",
    timezone: "America/Bogota",
    currency: "COP",
    minorUnits: 0,
  },
  reference: "2026-08-20T12:00:00-05:00",
  accounts: [
    {
      key: "bank",
      name: "Bancolombia",
      type: "ACCOUNT",
      openingBalance: 2000000,
      isDefault: true,
    },
  ],
  categories: [{ key: "outings", name: "Salidas", type: "EXPENSE" }],
  transactions: [
    {
      key: "dinner",
      type: "EXPENSE",
      amount: 100000,
      date: "2026-08-10T20:00:00-05:00",
      description: "Cena",
      category: "outings",
      from: "bank",
      note: "Split three ways in a currency with no cents: 33.333 each and the odd peso to you.",
    },
    {
      key: "party",
      type: "EXPENSE",
      amount: 100000,
      date: "2026-08-12T21:00:00-05:00",
      description: "Fiesta",
      category: "outings",
      from: "bank",
      note: "Three people and twenty guests: 23 parts, and the three left over are yours.",
    },
    {
      key: "taxi",
      type: "EXPENSE",
      amount: 60000,
      date: "2026-08-14T23:00:00-05:00",
      description: "Taxi",
      category: "outings",
      from: "bank",
    },
    {
      key: "lunch",
      type: "EXPENSE",
      amount: 45000,
      date: "2026-08-16T13:00:00-05:00",
      description: "Almuerzo",
      category: "outings",
      from: "bank",
    },
  ],
  contacts: [
    { key: "ana", name: "Ana" },
    { key: "beto", name: "Beto" },
    { key: "carla", name: "Carla" },
    { key: "dani", name: "Dani" },
    { key: "elena", name: "Elena" },
    { key: "fabio", name: "Fabio" },
  ],
  sharedGroups: [
    {
      key: "trip",
      name: "Cartagena",
      contacts: ["ana", "beto"],
      defaultMode: "EQUAL",
      writeOffs: ["beto"],
      note: "Beto is written off after every payment below, which is the order they are written in.",
      expenses: [
        {
          key: "e-dinner",
          transaction: "dinner",
          expect: { you: 33334, ana: 33333, beto: 33333 },
        },
        {
          key: "e-party",
          transaction: "party",
          mode: "EQUAL",
          guests: { count: 20, name: "La oficina" },
          shares: [
            { party: "you" },
            { party: "ana" },
            { party: "beto" },
            { party: "guests" },
          ],
          expect: { you: 4350, ana: 4347, beto: 4347, guests: 86956 },
        },
        {
          key: "e-taxi",
          transaction: "taxi",
          mode: "PERCENT",
          shares: [
            { party: "you", percent: 50 },
            { party: "ana", percent: 30 },
            { party: "beto", percent: 20 },
          ],
          expect: { you: 30000, ana: 18000, beto: 12000 },
        },
        {
          key: "e-lunch",
          transaction: "lunch",
          mode: "EXACT",
          shares: [
            { party: "you", fixedAmount: 25000 },
            { party: "ana", fixedAmount: 10000 },
            { party: "beto", fixedAmount: 10000 },
          ],
          expect: { you: 25000, ana: 10000, beto: 10000 },
        },
        {
          key: "e-tickets",
          paidBy: "ana",
          description: "Tickets",
          date: "2026-08-11T18:00:00-05:00",
          amount: 90000,
          expect: { you: 30000, ana: 30000, beto: 30000 },
          note: "Ana fronted this one, so no movement of yours exists for it and you owe her a third.",
        },
      ],
    },
    {
      key: "lunches",
      name: "Almuerzos de oficina",
      contacts: ["carla", "dani", "elena", "fabio"],
      defaultMode: "EQUAL",
      writeOffs: ["dani"],
      expect: {
        owedToYou: 48000,
        youOwe: 0,
        collected: 62000,
        writtenOff: 30000,
        status: "OPEN",
        people: {
          carla: { owesYou: 13000, state: "PARTIALLY_PAID" },
          dani: { owesYou: 0, state: "WRITTEN_OFF", ceiling: 35000 },
          elena: { owesYou: 0, surplus: 5000, state: "PAID" },
          fabio: { owesYou: 35000, state: "NOT_PAID" },
        },
      },
      note: "No movement of yours is linked here on purpose: this group is about the order a payment is imputed in, the rest of a fixed share, and what a write-off gives up on.",
      expenses: [
        {
          key: "l-tie-a",
          description: "Empanadas",
          date: "2026-08-06T12:00:00-05:00",
          amount: 25000,
          expect: {
            you: 5000,
            carla: 5000,
            dani: 5000,
            elena: 5000,
            fabio: 5000,
          },
          note: "Same instant as l-tie-b and a lower id, so a payment reaches it first. Written in that order too, so the file alone does not tell the tiebreak from the order of writing: what does is the unit test that hands the two lines over reversed.",
        },
        {
          key: "l-tie-b",
          description: "Bandejas",
          date: "2026-08-06T12:00:00-05:00",
          amount: 50000,
          expect: {
            you: 10000,
            carla: 10000,
            dani: 10000,
            elena: 10000,
            fabio: 10000,
          },
        },
        {
          key: "l-fixed",
          description: "Domicilio",
          date: "2026-08-07T12:00:00-05:00",
          amount: 60000,
          mode: "FIXED_REST",
          shares: [
            { party: "you", fixedAmount: 20000 },
            { party: "carla" },
            { party: "dani" },
            { party: "elena" },
            { party: "fabio" },
          ],
          expect: {
            you: 20000,
            carla: 10000,
            dani: 10000,
            elena: 10000,
            fabio: 10000,
          },
          note: "You take a fixed 20.000 and the other 40.000 is split four ways: the pinned figure never moves.",
        },
        {
          key: "l-back",
          description: "Almuerzo de la semana pasada",
          date: "2026-08-01T12:00:00-05:00",
          amount: 50000,
          expect: {
            you: 10000,
            carla: 10000,
            dani: 10000,
            elena: 10000,
            fabio: 10000,
          },
          note: "Written last and dated first: a payment covers THIS one before any of the ones above.",
        },
      ],
    },
  ],
  settlements: [
    {
      key: "ana-pays",
      with: "ana",
      date: "2026-08-18T10:00:00-05:00",
      collected: 40000,
      note: "Covers the dinner, then the party, then part of the taxi: oldest line first.",
    },
    {
      key: "guests-pay",
      with: "e-party",
      date: "2026-08-19T10:00:00-05:00",
      collected: 50000,
      outsideApp: true,
      note: "Cash the app never saw: no movement, and what counts as yours falls all the same.",
    },
    {
      key: "carla-pays",
      with: "carla",
      date: "2026-08-16T10:00:00-05:00",
      collected: 22000,
      note: "22.000 of the 35.000 she owes: the back-dated line first, then the older id of the two on the same instant, and 7.000 of the next.",
    },
    {
      key: "elena-pays",
      with: "elena",
      date: "2026-08-18T10:00:00-05:00",
      collected: 40000,
      note: "5.000 more than she owed: every line of hers is settled and the rest stays on the counter.",
    },
    {
      key: "dani-pays",
      with: "dani",
      date: "2026-08-21T10:00:00-05:00",
      collected: 5000,
      afterWriteOffs: true,
      note: "Paid after you had already given up on him: the write-off keeps its 35.000 ceiling and gives up 30.000.",
    },
  ],
  spending: [
    {
      name: "august-by-category",
      groupBy: "category",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "What is left as yours after everything that came back, never the amounts.",
    },
    {
      name: "august-by-day",
      groupBy: "day",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
    },
  ],
  lists: [
    {
      name: "august-newest-first",
      sort: "date",
      order: "desc",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      limit: 10,
      note: "The list is gross: a row's amount is what left the account. Asked by type, because the movements a settle-up writes carry ids the server mints and a fixture cannot name.",
    },
  ],
  budgets: [
    {
      key: "august",
      name: "Salidas de agosto",
      categories: ["outings"],
      amount: 400000,
      periodType: "MONTHLY",
      effectiveFrom: "2026-01-01T00:00:00-05:00",
      note: "Its spend is what counts as yours, so every payment lowers it in the month it happened.",
    },
  ],
};

export const SCENARIOS: Scenario[] = [bogota, madrid, tokyo, newYork, shared];
