/**
 * The parity scenarios, authored by hand. Every row is here because it breaks
 * a plausible shortcut in a client-side derivation — the `note` says which.
 *
 * Ids are fixed so the frontend's tests can hard-code them. Dates carry the
 * offset the user would have typed, never `Z`: a fixture about timezones that
 * states its instants in UTC hides exactly what it is meant to pin down.
 */
import { Scenario } from "./types";

/** `01930001-…-00000000a001`: scenario 1, kind `a` (account), number 1. */
export const fixtureId = (
  scenario: number,
  kind: "u" | "a" | "c" | "t" | "b",
  n: number,
): string =>
  `0193000${scenario}-0000-7000-8000-0000000${kind}${String(n).padStart(4, "0")}`;

const bogota: Scenario = {
  id: "cop-bogota",
  title: "COP · America/Bogota · zero-decimal currency, fixed −05:00 offset",
  pins: [
    "A day bucket is the day in the USER's timezone: 23:30 in Bogota is already tomorrow in UTC.",
    "A month window is [first day 00:00 local, next month 00:00 local) — not a UTC month.",
    "Deleted transactions leave every figure: totals, buckets, budgets and balances.",
    "ADJUSTMENT moves a balance but is excluded from spending unless asked for by name.",
    "TRANSFER moves two balances and is not spending.",
    "An archived category keeps its totals; archiving is not deleting.",
    "Quick-adds count as spending under `uncategorized`, and are the pending summary.",
    "Tag buckets double-count a transaction with two tags: their sum exceeds the total.",
    "With no `type`, the server means EXPENSE + INCOME + TRANSFER, everything but ADJUSTMENT.",
  ],
  user: {
    id: fixtureId(1, "u", 1),
    timezone: "America/Bogota",
    currency: "COP",
    minorUnits: 0,
  },
  reference: "2026-08-20T12:00:00-05:00",
  accounts: [
    {
      key: "bank",
      name: "Bancolombia",
      type: "ACCOUNT",
      color: "BLUE",
      openingBalance: 1_000_000,
      isDefault: true,
    },
    {
      key: "cash",
      name: "Cash",
      type: "CASH",
      color: "GRAY",
      openingBalance: 200_000,
    },
    {
      key: "card",
      name: "Visa Gold",
      type: "CARD",
      color: "PURPLE",
      openingBalance: -500_000,
    },
    {
      key: "savings",
      name: "Savings",
      type: "SAVINGS",
      color: "GREEN",
      openingBalance: 5_000_000,
    },
    {
      key: "closed",
      name: "Nequi",
      type: "OTHER",
      color: "PINK",
      openingBalance: 0,
      archived: true,
    },
  ],
  categories: [
    { key: "food", name: "Food", type: "EXPENSE" },
    { key: "transport", name: "Transport", type: "EXPENSE" },
    { key: "coffee", name: "Coffee", type: "EXPENSE" },
    { key: "trips", name: "Trips", type: "EXPENSE", archived: true },
    { key: "salary", name: "Salary", type: "INCOME" },
  ],
  transactions: [
    {
      key: "late-july-groceries",
      type: "EXPENSE",
      amount: 30_000,
      date: "2026-07-31T23:30:00-05:00",
      description: "Corner store",
      category: "food",
      from: "bank",
      tags: ["groceries"],
      note: "04:30Z on 2026-08-01: a UTC day bucket files it under August, the user under 31 July.",
    },
    {
      key: "salary",
      type: "INCOME",
      amount: 4_000_000,
      date: "2026-08-01T09:00:00-05:00",
      description: "August salary",
      category: "salary",
      to: "bank",
    },
    {
      key: "market",
      type: "EXPENSE",
      amount: 85_000,
      date: "2026-08-03T12:00:00-05:00",
      description: "Carulla groceries",
      category: "food",
      from: "bank",
      tags: ["groceries"],
    },
    {
      key: "same-day-coffee",
      type: "EXPENSE",
      amount: 9_800,
      date: "2026-08-03T19:45:00-05:00",
      description: "Pergamino",
      category: "coffee",
      from: "cash",
      tags: ["coffee"],
      note: "Second row of 2026-08-03, so that day's bucket has a count and an average.",
    },
    {
      key: "bus",
      type: "EXPENSE",
      amount: 12_000,
      date: "2026-08-05T08:15:00-05:00",
      description: "TransMilenio",
      category: "transport",
      from: "cash",
      tags: ["work"],
    },
    {
      key: "to-savings",
      type: "TRANSFER",
      amount: 500_000,
      date: "2026-08-10T10:00:00-05:00",
      description: "Monthly savings",
      from: "bank",
      to: "savings",
      note: "Moves two balances and is not spending.",
    },
    {
      key: "flight",
      type: "EXPENSE",
      amount: 250_000,
      date: "2026-08-12T16:20:00-05:00",
      description: "Avianca",
      category: "trips",
      from: "card",
      tags: ["travel"],
      note: "Its category is archived and it still counts.",
    },
    {
      key: "cash-count",
      type: "ADJUSTMENT",
      amount: 7_500,
      date: "2026-08-14T07:05:00-05:00",
      description: "Cash count correction",
      to: "cash",
      note: "Moves the balance; excluded from spending unless type=ADJUSTMENT is asked for.",
    },
    {
      key: "dinner",
      type: "EXPENSE",
      amount: 42_500,
      date: "2026-08-18T21:00:00-05:00",
      description: "Rappi dinner",
      category: "food",
      from: "card",
      note: "No tags: lands in the `untagged` bucket.",
    },
    {
      key: "latte",
      type: "EXPENSE",
      amount: 11_300,
      date: "2026-08-20T13:00:00-05:00",
      description: "Juan Valdez",
      category: "coffee",
      from: "card",
      tags: ["coffee", "latte"],
      note: "Two tags: counted once in the total, twice across the tag buckets.",
    },
    {
      key: "taxi",
      type: "EXPENSE",
      amount: 18_400,
      date: "2026-08-22T11:30:00-05:00",
      description: "Uber to work",
      category: "transport",
      from: "bank",
      tags: ["work"],
    },
    {
      key: "quick-lunch",
      type: "EXPENSE",
      amount: 12_500,
      date: "2026-08-24T18:00:00-05:00",
      quick: true,
      note: "Quick-add: no category, pending review, charged to the default account.",
    },
    {
      key: "quick-errand",
      type: "EXPENSE",
      amount: 20_000,
      date: "2026-08-25T18:30:00-05:00",
      quick: true,
    },
    {
      key: "refunded",
      type: "EXPENSE",
      amount: 99_000,
      date: "2026-08-26T12:00:00-05:00",
      description: "Returned purchase",
      category: "food",
      from: "bank",
      deleted: true,
      note: "Deleted: absent from every figure, and its balance effect is reversed.",
    },
    {
      key: "last-minute-coffee",
      type: "EXPENSE",
      amount: 4_700,
      date: "2026-08-31T23:30:00-05:00",
      description: "Tinto",
      category: "coffee",
      from: "cash",
      tags: ["coffee"],
      note: "04:30Z on 2026-09-01: inside August for the user, outside it in UTC.",
    },
  ],
  budgets: [
    {
      key: "everything",
      name: "Everything",
      categories: [],
      amount: 2_000_000,
      periodType: "MONTHLY",
      effectiveFrom: "2026-06-01T00:00:00-05:00",
      note: "Global: spends the window's whole expense, quick-adds included.",
    },
    {
      key: "food",
      name: "Food",
      categories: ["food"],
      amount: 150_000,
      periodType: "MONTHLY",
      effectiveFrom: "2026-06-01T00:00:00-05:00",
      override: 180_000,
      note: "The override applies to the reference period only; baseAmount stays 150 000.",
    },
    {
      key: "coffee",
      name: "Coffee",
      categories: ["coffee"],
      amount: 30_000,
      periodType: "WEEKLY",
      effectiveFrom: "2026-06-01T00:00:00-05:00",
      note: "ISO week (Monday-based) resolved in the user's timezone.",
    },
    {
      key: "transport",
      name: "Transport",
      categories: ["transport"],
      amount: 60_000,
      periodType: "BIWEEKLY",
      effectiveFrom: "2026-06-01T00:00:00-05:00",
      note: "Two-week grid anchored on the week of 2024-01-01, not on the budget.",
    },
    {
      key: "trip",
      name: "August trip",
      categories: ["trips"],
      amount: 300_000,
      periodType: "CUSTOM",
      periodStartDate: "2026-08-10T00:00:00-05:00",
      periodEndDate: "2026-08-31T00:00:00-05:00",
      note: "Its only category is archived: archivedCategoryIds is not empty.",
    },
    {
      key: "old-trip",
      name: "July trip",
      categories: ["transport"],
      amount: 100_000,
      periodType: "CUSTOM",
      periodStartDate: "2026-07-01T00:00:00-05:00",
      periodEndDate: "2026-08-01T00:00:00-05:00",
      note: "Expired at the reference instant: still listed, flagged.",
    },
    {
      key: "retired",
      name: "Retired budget",
      categories: ["coffee"],
      amount: 40_000,
      periodType: "MONTHLY",
      effectiveFrom: "2026-06-01T00:00:00-05:00",
      archived: true,
      note: "Archived: out of the views, present in the sync feed with archivedAt.",
    },
  ],
  spending: [
    {
      name: "august-by-category",
      groupBy: "category",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
    },
    {
      name: "august-by-tag",
      groupBy: "tag",
      type: "EXPENSE",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "The buckets add up to more than `total`: one transaction carries two tags.",
    },
    {
      name: "july-31-to-august-by-day",
      groupBy: "day",
      type: "EXPENSE",
      from: "2026-07-31T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "Widened by a day so the 31 July bucket shows up next to August's.",
    },
    {
      name: "august-by-category-untyped",
      groupBy: "category",
      from: "2026-08-01T00:00:00-05:00",
      to: "2026-09-01T00:00:00-05:00",
      note: "No `type`: income and the transfer are in, only ADJUSTMENT is out.",
    },
  ],
};

const madrid: Scenario = {
  id: "eur-madrid",
  title: "EUR · Europe/Madrid · two decimals and the spring DST jump",
  pins: [
    "Amounts with decimals only add up exactly in minor units: 0.10 + 0.20 + 19.99 + 2.30 is 22.59.",
    "A March window opens at +01:00 and closes at +02:00: its ends have different offsets.",
    "2026-03-29 is a 23-hour day — the local times 02:00–02:59 do not exist.",
    "A transaction 5 minutes into April is UTC-March: a UTC window would take it and drop the one on 1 March.",
    "An average is rounded in minor units: 20.29 over 3 rows is 6.76.",
  ],
  user: {
    id: fixtureId(2, "u", 1),
    timezone: "Europe/Madrid",
    currency: "EUR",
    minorUnits: 2,
  },
  reference: "2026-03-25T12:00:00+01:00",
  accounts: [
    {
      key: "current",
      name: "Cuenta corriente",
      type: "ACCOUNT",
      color: "BLUE",
      openingBalance: 1_000,
      isDefault: true,
    },
    {
      key: "card",
      name: "Tarjeta",
      type: "CARD",
      color: "RED",
      openingBalance: -250.5,
    },
  ],
  categories: [
    { key: "groceries", name: "Compra", type: "EXPENSE" },
    { key: "dining", name: "Restaurantes", type: "EXPENSE" },
    { key: "subs", name: "Suscripciones", type: "EXPENSE" },
    { key: "salary", name: "Nómina", type: "INCOME" },
  ],
  transactions: [
    {
      key: "first-minutes",
      type: "EXPENSE",
      amount: 10.1,
      date: "2026-03-01T00:15:00+01:00",
      description: "Mercadona",
      category: "groceries",
      from: "current",
      tags: ["compra"],
      note: "23:15Z on 28 February: inside March for the user, outside it in UTC.",
    },
    {
      key: "payday",
      type: "INCOME",
      amount: 1_500,
      date: "2026-03-05T09:00:00+01:00",
      description: "Nómina",
      category: "salary",
      to: "current",
    },
    {
      key: "before-the-jump",
      type: "EXPENSE",
      amount: 0.1,
      date: "2026-03-29T01:45:00+01:00",
      description: "Propina",
      category: "dining",
      from: "card",
      note: "15 minutes before the clocks jump from 02:00 to 03:00.",
    },
    {
      key: "after-the-jump",
      type: "EXPENSE",
      amount: 0.2,
      date: "2026-03-29T03:15:00+02:00",
      description: "Café",
      category: "dining",
      from: "card",
      note: "30 real minutes after the previous row, and 1h30 later on the clock.",
    },
    {
      key: "sunday-lunch",
      type: "EXPENSE",
      amount: 19.99,
      date: "2026-03-29T21:00:00+02:00",
      description: "Comida",
      category: "dining",
      from: "card",
      tags: ["finde"],
    },
    {
      key: "rounding",
      type: "EXPENSE",
      amount: 2.3,
      date: "2026-03-30T12:00:00+02:00",
      description: "Menú",
      category: "dining",
      from: "card",
      tags: ["finde"],
    },
    {
      key: "subscription",
      type: "EXPENSE",
      amount: 7.77,
      date: "2026-03-31T23:59:00+02:00",
      description: "Spotify",
      category: "subs",
      from: "current",
      note: "Last minute of March, local time.",
    },
    {
      key: "next-month",
      type: "EXPENSE",
      amount: 100,
      date: "2026-04-01T00:05:00+02:00",
      description: "Compra de abril",
      category: "groceries",
      from: "current",
      note: "22:05Z on 31 March: a UTC window would count it in March.",
    },
    {
      key: "void",
      type: "EXPENSE",
      amount: 50,
      date: "2026-03-20T12:00:00+01:00",
      description: "Devolución",
      category: "groceries",
      from: "current",
      deleted: true,
    },
    {
      key: "pending-coffee",
      type: "EXPENSE",
      amount: 3.45,
      date: "2026-03-27T17:00:00+01:00",
      quick: true,
    },
  ],
  budgets: [
    {
      key: "dining-month",
      name: "Restaurantes",
      categories: ["dining"],
      amount: 40,
      periodType: "MONTHLY",
      effectiveFrom: "2026-01-01T00:00:00+01:00",
    },
    {
      key: "dining-week",
      name: "Restaurantes (semana)",
      categories: ["dining"],
      amount: 25,
      periodType: "WEEKLY",
      effectiveFrom: "2026-01-01T00:00:00+01:00",
      note: "The week of the jump lasts 167 hours, not 168.",
    },
    {
      key: "everything",
      name: "Todo",
      categories: [],
      amount: 100,
      periodType: "MONTHLY",
      effectiveFrom: "2026-01-01T00:00:00+01:00",
    },
  ],
  spending: [
    {
      name: "march-by-category",
      groupBy: "category",
      type: "EXPENSE",
      from: "2026-03-01T00:00:00+01:00",
      to: "2026-04-01T00:00:00+02:00",
      note: "The window's ends carry different offsets. That is the point.",
    },
    {
      name: "march-by-day",
      groupBy: "day",
      type: "EXPENSE",
      from: "2026-03-01T00:00:00+01:00",
      to: "2026-04-01T00:00:00+02:00",
    },
  ],
};

const tokyo: Scenario = {
  id: "jpy-tokyo",
  title: "JPY · Asia/Tokyo · zero decimals, +09:00, quarter and year windows",
  pins: [
    "A local day starts at 15:00Z the day before: 00:10 on 1 April is 31 March in UTC.",
    "Quarter keys are `2026-Q2`; the year window is the local year, not 1 January UTC.",
    "A budget with no spend reports 0, not a missing figure.",
    "JPY has no minor unit: the amounts are the integers as typed.",
  ],
  user: {
    id: fixtureId(3, "u", 1),
    timezone: "Asia/Tokyo",
    currency: "JPY",
    minorUnits: 0,
  },
  reference: "2026-05-15T12:00:00+09:00",
  accounts: [
    {
      key: "bank",
      name: "銀行",
      type: "ACCOUNT",
      color: "BLUE",
      openingBalance: 500_000,
      isDefault: true,
    },
    {
      key: "wallet",
      name: "財布",
      type: "CASH",
      color: "GRAY",
      openingBalance: 20_000,
    },
  ],
  categories: [
    { key: "rent", name: "家賃", type: "EXPENSE" },
    { key: "transit", name: "交通", type: "EXPENSE" },
    { key: "gifts", name: "贈り物", type: "EXPENSE" },
    { key: "salary", name: "給与", type: "INCOME" },
  ],
  transactions: [
    {
      key: "march-rent",
      type: "EXPENSE",
      amount: 120_000,
      date: "2026-03-31T23:30:00+09:00",
      description: "3月家賃",
      category: "rent",
      from: "bank",
      note: "14:30Z: the last half hour of Q1 in Tokyo.",
    },
    {
      key: "first-ride",
      type: "EXPENSE",
      amount: 1_200,
      date: "2026-04-01T00:10:00+09:00",
      description: "定期",
      category: "transit",
      from: "wallet",
      note: "15:10Z on 31 March: Q2 for the user, Q1 in UTC.",
    },
    {
      key: "gift",
      type: "EXPENSE",
      amount: 8_800,
      date: "2026-04-15T12:00:00+09:00",
      description: "お祝い",
      category: "gifts",
      from: "wallet",
    },
    {
      key: "quarter-end",
      type: "EXPENSE",
      amount: 780,
      date: "2026-06-30T23:59:00+09:00",
      description: "バス",
      category: "transit",
      from: "wallet",
      note: "Last minute of Q2.",
    },
    {
      key: "next-quarter",
      type: "EXPENSE",
      amount: 15_000,
      date: "2026-07-01T00:01:00+09:00",
      description: "お中元",
      category: "gifts",
      from: "bank",
      note: "One minute into Q3: out of the quarter, inside the year.",
    },
    {
      key: "payday",
      type: "INCOME",
      amount: 350_000,
      date: "2026-04-25T09:00:00+09:00",
      description: "給与",
      category: "salary",
      to: "bank",
    },
    {
      key: "pending-lunch",
      type: "EXPENSE",
      amount: 500,
      date: "2026-05-02T12:30:00+09:00",
      quick: true,
    },
    {
      key: "void-ride",
      type: "EXPENSE",
      amount: 300,
      date: "2026-05-10T08:00:00+09:00",
      category: "transit",
      from: "wallet",
      deleted: true,
    },
  ],
  budgets: [
    {
      key: "transit-quarter",
      name: "交通",
      categories: ["transit"],
      amount: 5_000,
      periodType: "QUARTERLY",
      effectiveFrom: "2026-01-01T00:00:00+09:00",
    },
    {
      key: "year",
      name: "年間",
      categories: [],
      amount: 2_000_000,
      periodType: "YEARLY",
      effectiveFrom: "2026-01-01T00:00:00+09:00",
    },
    {
      key: "gifts-month",
      name: "贈り物",
      categories: ["gifts"],
      amount: 10_000,
      periodType: "MONTHLY",
      effectiveFrom: "2026-01-01T00:00:00+09:00",
      note: "May has no gift: the budget reports 0 spent.",
    },
  ],
  spending: [
    {
      name: "q2-by-category",
      groupBy: "category",
      type: "EXPENSE",
      from: "2026-04-01T00:00:00+09:00",
      to: "2026-07-01T00:00:00+09:00",
    },
    {
      name: "q2-by-day",
      groupBy: "day",
      type: "EXPENSE",
      from: "2026-04-01T00:00:00+09:00",
      to: "2026-07-01T00:00:00+09:00",
    },
  ],
};

const newYork: Scenario = {
  id: "usd-new-york",
  title: "USD · America/New_York · the repeated hour and an INCOME budget",
  pins: [
    "The autumn DST change repeats an hour: 01:30 happens twice on 2025-11-02, one real hour apart, and both are that same day.",
    "November opens at −04:00 and closes at −05:00: the month is 721 hours long, not 720.",
    "`avg` rounds half up in minor units: 10.01 over 2 rows is 5.01, not 5.00.",
    "A budget's `type` filters the rows: an INCOME budget ignores every expense in its own window.",
    "A query for `type: INCOME` groups income by category the same way expenses are grouped.",
  ],
  user: {
    id: fixtureId(4, "u", 1),
    timezone: "America/New_York",
    currency: "USD",
    minorUnits: 2,
  },
  reference: "2025-11-15T12:00:00-05:00",
  accounts: [
    {
      key: "checking",
      name: "Checking",
      type: "ACCOUNT",
      color: "BLUE",
      openingBalance: 2_500,
      isDefault: true,
    },
    {
      key: "credit",
      name: "Credit card",
      type: "CARD",
      color: "PURPLE",
      openingBalance: -875.25,
    },
  ],
  categories: [
    { key: "rent", name: "Rent", type: "EXPENSE" },
    { key: "dining", name: "Dining", type: "EXPENSE" },
    { key: "salary", name: "Salary", type: "INCOME" },
    { key: "freelance", name: "Freelance", type: "INCOME" },
  ],
  transactions: [
    {
      key: "first-hour",
      type: "EXPENSE",
      amount: 12.34,
      date: "2025-11-01T00:30:00-04:00",
      description: "Late dinner",
      category: "dining",
      from: "credit",
      note: "04:30Z on 1 November: still October in nothing, but the first row of the month locally.",
    },
    {
      key: "first-one-thirty",
      type: "EXPENSE",
      amount: 5,
      date: "2025-11-02T01:30:00-04:00",
      description: "Diner, before the clocks go back",
      category: "dining",
      from: "credit",
      note: "05:30Z. The first 01:30 of the day: the clocks have not gone back yet.",
    },
    {
      key: "second-one-thirty",
      type: "EXPENSE",
      amount: 5.01,
      date: "2025-11-02T01:30:00-05:00",
      description: "Diner, after the clocks go back",
      category: "dining",
      from: "credit",
      note: "06:30Z. The SECOND 01:30 of the same day: one real hour later, same reading on the clock.",
    },
    {
      key: "rent",
      type: "EXPENSE",
      amount: 1_850,
      date: "2025-11-03T09:00:00-05:00",
      description: "November rent",
      category: "rent",
      from: "checking",
    },
    {
      key: "paycheck",
      type: "INCOME",
      amount: 3_200,
      date: "2025-11-14T09:00:00-05:00",
      description: "Paycheck",
      category: "salary",
      to: "checking",
    },
    {
      key: "side-gig",
      type: "INCOME",
      amount: 450.5,
      date: "2025-11-21T16:00:00-05:00",
      description: "Invoice #14",
      category: "freelance",
      to: "checking",
    },
    {
      key: "quick-coffee",
      type: "EXPENSE",
      amount: 8.25,
      date: "2025-11-18T15:20:00-05:00",
      quick: true,
    },
    {
      key: "refunded",
      type: "EXPENSE",
      amount: 60,
      date: "2025-11-10T13:00:00-05:00",
      description: "Returned order",
      category: "dining",
      from: "credit",
      deleted: true,
    },
    {
      key: "last-minute",
      type: "EXPENSE",
      amount: 27.75,
      date: "2025-11-30T23:59:00-05:00",
      description: "Sunday takeout",
      category: "dining",
      from: "credit",
      note: "04:59Z on 1 December: the last minute of November for the user.",
    },
    {
      key: "next-month",
      type: "EXPENSE",
      amount: 99.99,
      date: "2025-12-01T00:10:00-05:00",
      description: "December groceries",
      category: "dining",
      from: "credit",
      note: "Ten minutes into December: out of every November figure.",
    },
  ],
  budgets: [
    {
      key: "income-goal",
      name: "Monthly income",
      type: "INCOME",
      categories: ["salary", "freelance"],
      amount: 3_500,
      periodType: "MONTHLY",
      effectiveFrom: "2025-01-01T00:00:00-05:00",
      note: "An INCOME budget: the 1 908.35 of expenses in the same window count for nothing here.",
    },
    {
      key: "dining",
      name: "Dining out",
      categories: ["dining"],
      amount: 60,
      periodType: "MONTHLY",
      effectiveFrom: "2025-01-01T00:00:00-05:00",
    },
    {
      key: "everything",
      name: "All spending",
      categories: [],
      amount: 2_500,
      periodType: "MONTHLY",
      effectiveFrom: "2025-01-01T00:00:00-05:00",
    },
  ],
  spending: [
    {
      name: "november-by-category",
      groupBy: "category",
      type: "EXPENSE",
      from: "2025-11-01T00:00:00-04:00",
      to: "2025-12-01T00:00:00-05:00",
      note: "721 hours: the window opens on daylight time and closes on standard time.",
    },
    {
      name: "november-by-day",
      groupBy: "day",
      type: "EXPENSE",
      from: "2025-11-01T00:00:00-04:00",
      to: "2025-12-01T00:00:00-05:00",
      note: "Both 01:30s land on 2025-11-02, and their average rounds half up.",
    },
    {
      name: "november-income-by-category",
      groupBy: "category",
      type: "INCOME",
      from: "2025-11-01T00:00:00-04:00",
      to: "2025-12-01T00:00:00-05:00",
    },
  ],
};

export const SCENARIOS: Scenario[] = [bogota, madrid, tokyo, newYork];
